#!/bin/bash

mkdir -p "./1/$1"
mkdir -p "./2/$1"
mkdir -p "./2push/$1"
wget --no-clobber --page-requisites --adjust-extension --convert-links --restrict-file-names=nocontrol --remote-encoding --no-parent --span-hosts --no-directories --directory-prefix=./1/$1/ $1
#iconv -f ISO-8859-1 -t UTF-8 "./http1/$1/index.html" > "./http1/$1/index-temp.html"
#rm "./http1/$1/index.html"
#mv "./http1/$1/index-temp.html" "./http1/$1/index.html"
cp -R ./1/$1/* "./2/$1/"
cp -R ./1/$1/* "./2push/$1/"
echo '<Files "index.html">' > "./2push/$1/.htaccess"
ls -1 --color=never --ignore="index.html" "./2push/$1/" | while read line; do
    echo '    Header always set Access-Control-Allow-Origin "*"';
    echo '    Header always set Access-Control-Allow-Methods "GET, OPTIONS"';
    echo "    Header set X-Frame-Options SAMEORIGIN";
    echo -n "    Header add Link '</$1/$line>;rel=preload;as=";
    filename=$(basename "$line");
    ext=${filename##*.};
    case "$ext" in # According to https://w3c.github.io/preload/#attributes
        "aac" | "aiff" | "flac" | "m4a" | "mp3" | "ogg" | "wav" | "wma") # Audio formats
            echo -n "media"
        ;;
        "3gp" | "amv" | "avi" | "flv" | "gifv" | "m4v" | "mkv" | "mov" | "mp4" | "mpg" | "mpeg" | "ogv" | "vob" | "webm" | "wmv") # Video formats
            echo -n "media"
        ;;
        "js")
            echo -n "script"
        ;;
        "css")
            echo -n "style"
        ;;
        "ttf" | "woff" | "abf" | "dfont" | "sfd" | "fnt" | "mf" | "otf" | "pfb")
            echo -n "font"
        ;;
        "png" | "jpeg" | "jpg" | "dds" | "tiff" | "bmp" | "tif" | "thumb" | "gif" | "tga" | "jpe" | "jfif")
            echo -n "image"
        ;;
        "vsdx" | "svg")
            echo -n "image"
        ;;
        "swf")
            echo -n "embed"
        ;;
        "html" | "htm" | "xhtml" | "php")
            echo -n "document"
        ;;
        *) # Default behaviour
        echo -n "object"
        ;;
    esac
    echo "'";
done >> "./2push/$1/.htaccess"
echo '</Files>' >> "./2push/$1/.htaccess"
