#!/bin/bash

mkdir -p "./1/$1"
mkdir -p "./2/$1"
mkdir -p "./2push/$1"
wget --no-clobber --page-requisites --adjust-extension --convert-links --restrict-file-names=nocontrol --remote-encoding --no-parent --span-hosts --backup-converted --no-directories --directory-prefix=./1/$1/ $1
#iconv -f ISO-8859-1 -t UTF-8 "./http1/$1/index.html" > "./http1/$1/index-temp.html"
#rm "./http1/$1/index.html"
#mv "./http1/$1/index-temp.html" "./http1/$1/index.html"
cp -R ./1/$1/* "./2/$1/"
cp -R ./1/$1/* "./2push/$1/"
