#!/bin/bash

# Check if root user
if [[ `id -u` -ne 0 ]] ; then echo "This script must be run as root" ; exit 1 ; fi

# Delete past root class
tc qdisc del dev eth0 root

# Create the default root class
tc qdisc add dev eth0 handle 1: root htb

# Create children classes
tc class add dev eth0 parent 1: classid 1:11 htb rate 1000Mbps
tc class add dev eth0 parent 1: classid 1:12 htb rate 1000Mbps
tc class add dev eth0 parent 1: classid 1:13 htb rate 1000Mbps

# Apply rules on classes
tc qdisc add dev eth0 parent 1:11 handle 10: netem delay "$1ms"
tc qdisc add dev eth0 parent 1:12 handle 20: netem delay "$1ms"
tc qdisc add dev eth0 parent 1:13 handle 30: netem delay "$1ms"

# Apply filters
tc filter add dev eth0 protocol ip prio 1 u32 match ip sport 8081 0xffff flowid 1:11
tc filter add dev eth0 protocol ip prio 1 u32 match ip sport 8082 0xffff flowid 1:12
tc filter add dev eth0 protocol ip prio 1 u32 match ip sport 8083 0xffff flowid 1:13

"$1" > ./app/currentDelay.txt