#!/bin/bash

mkdir 1
mkdir 2
mkdir 2push

cat > ./1/.htaccess <<- EOM
Require all granted
Options +Indexes
Header unset ETag
Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
Header set Pragma "no-cache"
EOM

cat > ./2/.htaccess <<- EOM
Protocols h2 http/1.1
H2Push Off
Require all granted
Options +Indexes
Header unset ETag
Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
Header set Pragma "no-cache"
EOM

cat > ./2push/.htaccess <<- EOM
Protocols h2 http/1.1
H2Push on
H2PushDiarySize 0 # We don't want the server to cache pushed resources if TCP connection is maintained through tests
Require all granted
Options +Indexes
AllowOverride All
Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
Header set Pragma "no-cache"
EOM